name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

permissions:
  # by default, no access to anything
  contents: none

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
        permissions:
          contents: read
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.11.0'

      - name: run docker-based ci
        run: just docker-ci
